### ISSUE TITLE
Error on pack

### ISSUE THREAD

**Issue by xRevan116x** [d00telemental/LECoal#1]
Was working earlier today, I did not change the syntax.
Re-downloaded release build.

command line output below:

C:\LECoalLatest-Built>.\lecoal.exe pack "F:\Game files\MELE\Mod\me2_unpacked" "C:\tmp"
Packing F:\Game files\MELE\Mod\me2_unpacked
  into C:\tmp...
Error in bundle reading/writing logic:
Expected to have exactly two chunks after splitting the line by =

    at LECoal.CoalescedBundle.ReadFromDirectory(String name, String path)
    at LECoal.CoalescedTool.Pack(String fromDir, String toFile)
    at LECoal.CoalescedTool..ctor(String[] args)
    at LECoal.Program.Main(String[] args)

**Comment by d00telemental** [comment]
Attach a ZIP of the directory you are trying to pack
